name: refreshed
description: "Enhanced GetX for Flutter: Stability, Performance, Beginner-Friendly."
version: 2.3.0
repository: "https://github.com/Aniketkhote/refreshed"

environment:
  sdk: ">=3.2.6 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ">=0.4.0 <0.6.0"

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
