name: refreshed
description: "Enhanced GetX for Flutter: Stability, Performance, Beginner-Friendly."
version: 2.0.0
repository: "https://github.com/Aniketkhote/refreshed"

environment:
  sdk: ">=3.2.6 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: any

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
