name: refreshed
description: "Enhanced GetX for Flutter: Stability, Performance, Beginner-Friendly."
version: 2.10.0
repository: "https://github.com/Aniketkhote/refreshed"

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ">=1.0.0 <2.0.0"

dev_dependencies:
  flutter_lints: ">=4.0.0 <6.0.0"
  flutter_test:
    sdk: flutter

flutter:
