name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Cache Flutter dependencies
      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      # Setup Flutter environment
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.0"
          channel: "stable"

      # Run flutter doctor to verify the setup
      - run: flutter doctor

      # Install dependencies
      - run: dart pub get

      # Optional: Upgrade dependencies to latest compatible versions
      - run: dart pub upgrade

      # Run static code analysis
      - run: dart analyze

      # Run unit tests and widget tests
      - run: dart test

      # Optional: Run tests with coverage
      # - run: flutter test --coverage

      # Optional: Upload coverage reports to Codecov
      # - uses: codecov/codecov-action@v4
